algo = input('Digite algo:\n')
print('É espaço?', algo.isspace())
print('É alphanúmerico?', algo.isalnum())
print('É alfabetíco?', algo.isalpha())
print('Está minúsculo?', algo.islower())
print('É um número?', algo.isnumeric())
print('Está em maiúscula?', algo.isupper())
print('Está capitalizada?',algo.istitle())
