nome = str(input('Digite o seu nome: ')).strip()
dividido = nome.split()
print('Analisando o seu nome ...')
print('O seu nome em maiúsculas é {}'.format(nome.upper()))
print('O seu nome em minúsculas é {}'.format(nome.lower()))
print('O seu nome ao todo contém {} letras'.format(len(nome) - nome.count(' ')))
#print('Seu primeiro nome contém {} letras'.format(nome.find(' ')))
print('Seu primeiro nome é {}, e contém {} letras'.format(dividido[0], len((dividido[0][::]))))
